# Generated by Django 4.1.7 on 2023-03-04 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condominio',
            name='Fundo_reserva',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='Taxa_condominio',
            field=models.FloatField(default=0),
        ),
    ]
