# Generated by Django 4.1.7 on 2023-03-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0002_alter_condominio_fundo_reserva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='morador',
            name='apto_sala',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
