# Generated by Django 4.1.7 on 2023-03-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0004_condominio_mostrar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condominio',
            name='Fundo_reserva',
        ),
        migrations.RemoveField(
            model_name='condominio',
            name='Taxa_condominio',
        ),
        migrations.AddField(
            model_name='bloco',
            name='Fundo_reserva',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bloco',
            name='Taxa_condominio',
            field=models.FloatField(default=0),
        ),
    ]
