# Generated by Django 4.1.7 on 2023-03-13 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('condominio', '0005_remove_condominio_fundo_reserva_and_more'),
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomes', models.CharField(max_length=6)),
                ('valor', models.FloatField(default=0)),
                ('tipo_calculo', models.CharField(choices=[('SIM', 'Simples'), ('RAT', 'Rateio'), ('RAA', 'Rateio Água'), ('RAG', 'Rateio Gás')], max_length=3)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.contas')),
                ('morador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condominio.morador')),
            ],
            options={
                'verbose_name': 'Calculo',
                'verbose_name_plural': 'Calculos',
            },
        ),
    ]
